server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/automationtest
    username: user
    password: 123456
  docker:
    compose:
      file: ./dockerfiles/docker-compose.yml