services:
  postgres:
    image: 'postgres:latest'
    container_name: automationtest-sql-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5434:5432'
    volumes:
      - ./db_automationtest_data:/var/lib/postgresql/data
    command: [ "postgres", "-c", "max_connections=400" ]
volumes:
  db_automationtest_data: { }